### PR TITLE
Upgrade to future-spec alpha17

### PR DESCRIPTION
**Pull request by iwillig**

### CODE REVIEW

**Comment by bcarrell** [comment]
Hmm, I wonder why I don't see CircleCI test feedback for this PR.

**Comment by bcarrell** [comment]
@hlship Have you configured CircleCI for running tests from forks?

**Comment by hlship** [comment]
I think I do not have that on (circle CI).  One reason is that people have been using it to mine bitcoin !

**Comment by hlship** [comment]
As expected, ran tests locally, no problems.

**Comment by bcarrell** [comment]
Seems pretty tame to run pull request builds IMO.

**Comment by iwillig** [comment]
@hlship good point. Will get to those when I have a free second.

**Comment by bcarrell** [comment]
@iwillig If you're busy, I can make these updates for you.  Let me know.

**Comment by iwillig** [comment]
@bcarrell I don't not mind! Thanks

**Comment by bcarrell** [comment]
I'll go ahead and merge this and update the relevant documentation in a separate commit.  Thanks!

**Pull request merged**
